---
- name: Setup Linux workstation
  hosts: localhost
  connection: local
  gather_facts: true
  # TODO: remove and only add to specific tasks that require sudo
  become: true

  tasks:
    - name: Record the current logged-in user that invoked the playbook
      ansible.builtin.set_fact:
        invoking_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"

    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ ansible_distribution | lower }}-workstation"

    - name: Enable password-less sudo
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ invoking_user }}"
        mode: "0440"
        owner: root
        group: root
        content: "{{ invoking_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"
    # - name: Generate SSH keys locally (using a role)
    # - name: Make sure the line Host * AddKeysToAgent yes is present in ~/.ssh/config
    - name: Ensure dnf.conf exists and has a [main] section
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        create: true
        line: "[main]"
        owner: root
        group: root
        mode: '0644'

    - name: Configuring and improving DNF
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        marker: "# {mark} Ansible block: configuring DNF"
        insertafter: '^\[main\]'
        block: |
          fastestmirror=True
          max_parallel_downloads=10
          defaultyes=True
          keepcache=True

    - name: Create directories
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        owner: "{{ invoking_user }}"
        group: "{{ invoking_user }}"
        mode: "0755"
      loop:
        - Work
        - Projects

    # - name: Import a task or role for configuring GNOME

    - name: Remove Firefox
      ansible.builtin.package:
        state: absent
        name: firefox

    - name: Install packages
      ansible.builtin.dnf5:
        update_cache: true
        state: present
        name:
          - htop
          - tmux
          - stow

    - name: Symlink dotfiles with GNU Stow
      ansible.builtin.shell:
        chdir: "{{ home_dir }}/.dotfiles/Applications"
        cmd: stow -v */
      register: stow_result
      changed_when: ("LINK:" in stow_result.stdout) or ("LINK:" in stow_result.stderr)

    # - name: Copy wallpaper file
    #   ansible.builtin.copy:
    #     src: files/wallpaper.png
    #     dest: /usr/share/background/ansible-wallpaper.png
    #     owner: root
    #     group: root
    #     mode: u+rw

    # - name: Set wallpaper
    #   community.general.dconf:
    #     state: present
    #     key: "/org/gnome/desktop/background/picture-uri"
    #     value: "'file:///usr/share/background/ansible-wallpaper.png'"

        # python3-psutil needs to be installed from apt for the dconf module
        # Install from apt the dconf-cli and then do dconf dump / > settings.txt to see all configs
