- name: Main machine setup
  hosts: localhost
  connection: local
  # become: true
  vars:
    # the_os_type: "{{ ansible_facts["distribution"] }}"

  pre_tasks:
    - name: Update cache (apt)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      # when: os_type == "Ubuntu"
      when: ansible_facts["distribution"] == "Ubuntu"
      tags:
        - apps/packages
        # - scripts
        # - homebrew
        # - zsh
        # - node
        # - python
        # - go
    - name: Update cache (Homebrew)
      community.general.homebrew:
        update_homebrew: true
      changed_when: false
      # when: os_type == "MacOSX"
      when: ansible_facts["distribution"] == "MacOSX"
      tags:
        - apps/packages

  tasks:
    - ansible.builtin.include_tasks: tasks/homebrew.yml
    # - ansible.builtin.include_tasks: tasks/zsh.yml
    # - ansible.builtin.include_tasks: tasks/node.yml
# use which clause for different OSes
