- name: Main development machine setup
  hosts: localhost
  connection: local
  vars:
    os: ansible_facts["os_family"]

  pre_tasks:
  - name: Update package manager cache (Homebrew)
    when: os == "Darwin"
    changed_when: false
    tags:
      - apps/packages
    community.general.homebrew:
      update_homebrew: true
    
  - name: Update package manager cache (apt)
    when: os == "Debian"
    changed_when: false
    tags:
      - apps/packages
    ansible.builtin.apt:
      update_cache: true

  tasks:
  - name: Tasks common to Unix systems (not Windows)
    when: os != "Windows"
    ansible.builtin.include_tasks: tasks/unix.yml

  - name: MacOS machine setup
    when: os == "Darwin"
    ansible.builtin.include_tasks: tasks/macos/macos.yml
      
  - name: Linux machine setup
    when: os == "Debian"
    ansible.builtin.include_tasks: tasks/linux/linux.yml

  # - name: Windows machine setup
  #   when: os == "Windows"
  #   ansible.builtin.include_tasks:
      