git:
  paging:
    # see: delta --help
    pager: delta --paging=never --side-by-side --file-style=omit --hunk-header-decoration-style=ul --hunk-header-style=file --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    colorArg: always

gui:
  nerdFontsVersion: "3"
  # other Catppuccin flavours and accents at: https://github.com/catppuccin/lazygit/tree/main/themes
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
