- name: Check if the destination directory already exists
  ansible.builtin.stat:
    path: "{{ item.repo_dest }}"
  register: repo_dest_dir

- name: Clone the repo if not cloned before
  when: repo_dest_dir.stat.isdir is not defined
  ansible.builtin.git:
    clone: true
    repo: "{{ item.repo_URL }}"
    dest: "{{ item.repo_dest }}"
    update: false
