# NOTE: this needs to come after the tasks that installs Git
- name: Check if tpm directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
  register: tpm_dir

- name: Clone tpm repo if directory doesn't exist
  when: tpm_dir.stat.isdir is not defined
  ansible.builtin.git:
    clone: true
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
    update: false
  register: tpm_cloned

  # NOTE: assume tmux.conf has been symlinked already
- name: Install tmux plugins
  # execute only when tpm is installed the first time
  when: tpm_cloned.changed is true
  changed_when: tpm_plugins_installed.rc is defined
  ansible.builtin.command: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm/bin/install_plugins"
  register: tpm_plugins_installed

# - name: Keep tmux plugins up to date
#   when: 
#   # assume constant change to keep plugins always up to date
#   changed_when: true
#   ansible.builtin.command: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm/bin/update_plugins all"
