- name: 1. Install essential brews
  tags: homebrew
  community.general.homebrew:
    name: "{{ lookup('file', 'homebrew_brews.txt') | replace('\n', ',') }}"
    state: present

- name: 2. Install essential casks
  tags: homebrew
  community.general.homebrew_cask:
    name: "{{ lookup('file', 'homebrew_casks.txt') | replace('\n', ',') }}"
    state: present
    install_options: no-quarantine

# NOTE: 'homebrew_cask' module is used because 'homebrew' is
# problematic for casks: e.g. failing if the cask is already installed.
