- name: Make sure the required 'plistlib' library is installed
  ansible.builtin.pip:
    # virtualenv: "{{ ansible_env.HOME }}/ansible-temp/ansible-setup"
    name: plistlib
    state: present

- name: Make sure the ~/Scripts directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/Scripts"
  register: scripts_directory

  # TODO: change the location of .plist files to the .dotfiles repo?
- name: Deploy the custom job definitions (.plist files)
  when: scripts_directory.stat.isdir is defined and scripts_directory.stat.isdir
  ansible.builtin.file:
    state: link
    src: "{{ ansible_env.HOME }}/Scripts/periodic_scripts/{{ item }}.plist"
    dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/{{ item }}.plist"
  with_items: "{{ lookup('file', 'launchd_agents.txt') }}"

# TODO: does this even work for user agents (as opposed to system-wide services?)
# TODO: the syntax is different for enabling and starting agents. Can this resolve it automatically?
- name: Enable and start launchd agents
  community.general.launchd:
    enabled: true
    state: started
    name: "{{ item }}"
  with_items: "{{ lookup('file', 'launchd_agents.txt') }}"
