---
- name: Setup Linux workstation
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Record the current logged-in user that invoked the playbook and their home directory
      ansible.builtin.set_fact:
        invoking_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"

    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ ansible_distribution | lower }}-workstation"

    - name: Enable password-less sudo
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ invoking_user }}"
        mode: "0440"
        owner: root
        group: root
        content: "{{ invoking_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    # - name: Generate SSH keys locally (using a role)
    # - name: Make sure the line Host * AddKeysToAgent yes is present in ~/.ssh/config

    - name: Ensure dnf.conf exists and has a [main] section (for configuration)
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        create: true
        line: "[main]"
        owner: root
        group: root
        mode: '0644'

    - name: Configuring and improving DNF
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        marker: "# {mark} Ansible block: configuring DNF"
        insertafter: '^\[main\]'
        block: |
          fastestmirror=True
          max_parallel_downloads=10
          defaultyes=True
          keepcache=True

    # - name: Import a task or role for configuring GNOME

    - name: Remove Firefox
      ansible.builtin.package:
        state: absent
        name: firefox

      # TODO: convert this to the yum_repository module instead
      # TODO: might actually install Nushell from Homebrew
    - name: Add the Nushell repository for dnf installation
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/fury-nushell.repo
        owner: root
        group: root
        mode: '0644'
        content: |
          [gemfury-nushell]
          name=Gemfury Nushell Repo
          baseurl=https://yum.fury.io/nushell/
          enabled=1
          gpgcheck=0
          gpgkey=https://yum.fury.io/nushell/gpg.key

    # TODO: use ansible.builtin.yum_repository in a block to add the repo first then install terra-release
    - name: Add Yum repository for Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: '0644'

    # TODO: add the rpm fusion repos and the nushell repo this way too (and even others like librewolf and chrome and vscode)
    - name: Add the Terra (terra-release) repository
      ansible.builtin.command:
        cmd: dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release -y
        creates: /etc/yum.repos.d/terra.repo

    - name: Install Homebrew
      become: false
      ansible.builtin.shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        creates: /home/linuxbrew/.linuxbrew/bin/brew
      environment:
        NONINTERACTIVE: "1"

    - name: Install essential packages
      ansible.builtin.dnf5:
        update_cache: true
        state: present
        name:
          - dnf-plugins-core
          # - stow TODO: remove!
          # from Terra
          - ghostty
          # from custom developer repos
          - nushell
            # Install the latest version of Docker
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Start the Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add the current user to the newly created 'docker' group (to avoid sudo)
      # Log out then back in for group membership to be re-evaluated
      ansible.builtin.user:
        name: "{{ invoking_user }}"
        append: true
        groups:
          - docker

    # - name: Install all the flatpaks using the flatpak module

    - name: Make sure Nushell is present in the list of shells
      ansible.builtin.lineinfile:
        state: present
        path: /etc/shells
        line: "/usr/bin/nu"

    - name: "Make Nushell the default interactive shell for {{ invoking_user }}"
      ansible.builtin.user:
        state: present
        name: "{{ invoking_user }}"
        shell: /usr/bin/nu

    # - name: Set wallpaper
    #   community.general.dconf:
    #     state: present
    #     key: "/org/gnome/desktop/background/picture-uri"
    #     value: "'file:///usr/share/background/ansible-wallpaper.png'"

        # python3-psutil needs to be installed from apt for the dconf module
        # Install from apt the dconf-cli and then do dconf dump / > settings.txt to see all configs
