{ pkgs, ... }:

{
  imports = [
    # Host-specific hardware modules
    ./hardware/hardware-configuration.nix # generated by nixos-generate-config: regenerate, don't hand-edit
    ./hardware/storage.nix # hand-maintained disk config (swap LUKS + NTFS data drives)
    ./hardware/alsa-realtek-fix.nix # workarounds for the onboard Realtek ALC887-VD codec muting itself
    ./hardware/nvidia.nix # GTX 1070 Ti (Pascal): legacy_580 driver + the LTS kernel pin it forces

    # System-level modules
    ../../nixos-modules/fonts.nix
    ../../nixos-modules/nh.nix
    ../../nixos-modules/zsa.nix
    ../../nixos-modules/locale.nix
    ../../nixos-modules/audio.nix
    ../../nixos-modules/networking.nix
    ../../nixos-modules/tailscale.nix
    ../../nixos-modules/nix-settings.nix
    ../../nixos-modules/nix-ld.nix
    ../../nixos-modules/helium.nix
    ../../nixos-modules/localsend.nix
    ../../nixos-modules/qbittorrent.nix
    ../../nixos-modules/plasma.nix # desktop environment - swap to try another DE
  ];

  networking.hostName = "nixos-workstation";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users = {
    murtadha = {
      isNormalUser = true;
      description = "Murtadha";
      shell = pkgs.nushell; # login shell for this user (other accounts keep system default - bash)
      extraGroups = [
        "networkmanager"
        "wheel"
      ];
    };
  };
  # Register Nushell as a valid login shell (required for it to be usable above)
  environment.shells = [ pkgs.nushell ];

  # No autoLogin on purpose: SDDM's password login goes through the `login` PAM
  # stack, where kwallet-pam unlocks the wallet with the typed password. With
  # autoLogin no password ever reaches PAM, so the wallet stays locked and the
  # first app needing it (browser, ssh askpass) throws a password prompt instead.

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Install Steam
  programs.steam.enable = true;

  # List packages installed in system profile.
  environment.systemPackages = with pkgs; [
    wget
    git
    curl
    vim
  ];

  # ONLY bump up on fresh installs!
  system.stateVersion = "25.05";
}
