theme = "catppuccin_mocha"

[editor]
scrolloff = 7                     # default is 5
cursorline = true
color-modes = true
true-color = true                 # to override auto-detection in cases of false negatives
bufferline = "multiple"
end-of-line-diagnostics = "error"
scroll-lines = 1                  # default is 3
popup-border = "all"              # other options: popup, menu, or none
# shell = ["nu", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["version-control"]

[editor.inline-diagnostics]
cursor-line = "hint"
prefix-len = 3       # default is 1

[keys.normal]
# Esc for 3 purposes: to close, to deselect (;), and to collapse to one cursor (,)
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":quit"
w = ":write" # this overwrites Space + w for 'Window' menu

[editor.lsp]
# display-inlay-hints = true
