[[language]]
name = "nix"
auto-format = true
language-servers = ["nixd", "nil"]

[language-server.nixd]
command = "nixd"
args = ["--semantic-tokens=true"]

[language-server.nixd.config.nixd]
nixpkgs = { expr = "import (builtins.getFlake \"/Users/murtadha/.dotfiles/system-setup/nix/\").inputs.nixpkgs {}" }
formatting = { command = ["nixfmt"] }

[language-server.nixd.config.nixd.options]
home-manager = { expr = "(builtins.getFlake \"/Users/murtadha/.dotfiles/system-setup/nix/\").homeConfigurations.\"murtadha@MacBookPro.localdomain\".options" }
nixos = { expr = "(builtins.getFlake \"/Users/murtadha/.dotfiles/system-setup/nix/\").nixosConfigurations.nixos-workstation.options" }

[[language]]
name = "hcl"
auto-format = true

[[language]]
name = "tfvars"
auto-format = true

[[language]]
name = "python"
auto-format = true

# NOTE: all config below is copy-pasted
[[language]]
name = "go"
auto-format = true
language-servers = ["gopls", "golangci-lint-lsp"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path",
  "stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-astro",
  "--parser",
  "astro",
] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/Users/murtadha/.cache/.bun/install/global/node_modules/typescript/lib" } }
