tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Modern replacement for 'ls'
brew "exa"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Pager program similar to more
brew "less"
# Mac App Store command-line interface
brew "mas"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Framework for layout and rendering of i18n text
brew "pango"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Tool Command Language
brew "tcl-tk"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# Memory training application
cask "anki"
# Display management tool
cask "betterdisplay"
# Screen capturing tool
cask "cleanshot"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# App to build and share containerized applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Git client focusing on productivity
cask "gitkraken"
# Free and open-source media player
cask "iina"
# System monitoring app
cask "istat-menus"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# JetBrains tools manager
cask "jetbrains-toolbox"
# GPU-based terminal emulator
cask "kitty"
# Explore and manipulate your MongoDB data
cask "mongodb-compass"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Open source virtual/remote desktop application
cask "rustdesk"
# Instant messaging application focusing on security
cask "signal"
# Real time file synchronization software
cask "syncthing"
# Customizable email client
cask "thunderbird"
# Git client focusing on power and productivity
cask "tower"
# Virtual machines UI using QEMU
cask "utm"
# Rust-based terminal
cask "warp"
# Video communication and virtual meeting platform
cask "zoom"
# Collect, organize, cite, and share research sources
cask "zotero"
mas "AdGuard for Safari", id: 1440147259
mas "Bitwarden", id: 1352778147
mas "Craft", id: 1487937127
mas "Dark Noise", id: 1465439395
mas "Dark Reader for Safari", id: 1438243180
mas "Darkroom", id: 953286746
mas "GoodLinks", id: 1474335294
mas "GoodNotes", id: 1444383602
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keka", id: 470158793
mas "Keynote", id: 409183694
mas "MarginNote 3", id: 1423522373
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Word", id: 462054704
mas "NCalc Fx", id: 1449106995
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Things", id: 904280696
