# export BREW_PREFIX=$(brew --prefix) # Save Homebrew’s installed location
export HOMEBREW_NO_ANALYTICS=1  # Disable Homebrew Google analytics
export HOMEBREW_CASK_OPTS="--no-quarantine" # Disable Apple "trusted app" post-installation dialogues
export NULLCMD=bat  # Default to bat instead of cat
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml" # Starship config
export POETRY_CONFIG_DIR="$HOME/.config/pypoetry"  # poetry config directory
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"  # pyenv root directory
export VOLTA_HOME="$XDG_DATA_HOME/volta"  # Volta root directory
export GOENV_ROOT="$XDG_DATA_HOME/goenv"  # goenv root directory
# export GOENV_GOPATH_PREFIX="$HOME/go"  # the default prefix for GOPATH
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"  # Vagrant root directory
# export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"  # Docker
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"  # less history directory
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"  # Jupyter config directory