# export BREW_PREFIX=$(brew --prefix) # Save Homebrew’s installed location
export HOMEBREW_NO_ANALYTICS=1  # Disable Homebrew Google analytics
export HOMEBREW_CASK_OPTS="--no-quarantine" # Disable Apple "trusted app" post-installation dialogues
export NULLCMD=bat  # Default to bat instead of cat
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml" # Starship config
export POETRY_CONFIG_DIR="$HOME/.config/pypoetry"  # poetry config directory
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"  # pyenv root directory
export VOLTA_HOME="$XDG_DATA_HOME/volta"  # Volta root directory
export GOBREW_ROOT="$XDG_DATA_HOME/gobrew"  # gobrew root directory
export GOROOT="$GOBREW_ROOT/.gobrew/current/go"  # Set GOROOT according to the active version of Go set by gobrew
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"  # Vagrant root directory
# export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"  # Docker
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"  # less history directory
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"  # Jupyter config directory
# fzf Catppuccin (Mocha) colours: https://github.com/catppuccin/fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"