- name: Install ZSH with Homebrew
  tags: apps/packages
  community.general.homebrew:
    name: zsh
    state: present

- name: Make it the default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ ansible_env.HOMEBREW_PREFIX }}/bin/zsh"
    # It seems there is no need to include the path in /etc/shells

# NOTE: ansible_env is used to access env variables on the remote machine.
# It's part of ansible facts collected about the remote node.

# NOTE: lookup always accesses data on the control node, but
# the control node and the remote node are the same machine here.

# - name: Install Homebrew packages
#   register: brewfile_cmd_output
#   ansible.builtin.shell:
#     cmd: export HOMEBREW_CASK_OPTS="--no-quarantine" && brew bundle install --verbose --file=./Homebrew/Brewfile

- name: Install all apps and packages
  block:
    - name: Install brews
      tags: apps/packages
      community.general.homebrew:
        name: "{{ lookup('file', 'homebrew_brews.txt') | replace('\n', ',') }}"
        state: present

    # TODO: this task is causing all sorts of issues, from failing if the cask exists to failing due to Mac gatekeeping nonesense
    - name: Install casks
      tags: apps/packages
      environment:
        HOMEBREW_CASK_OPTS: --no-quarantine
      community.general.homebrew:
        name: "{{ lookup('file', 'homebrew_casks.txt') | replace('\n', ',') }}"
        state: present

    # TODO: come back after testing to work on this task
    # - name: Install App Store apps with mas
      # community.general.mas:

- name: Symlink all dotfiles using a script
  tags: dotfiles
  ansible.builtin.script:
    cmd: dotfiles.sh

# command -v stow 1>/dev/null 2>/dev/null && [[ $(basename $(pwd))=="Applicatios" ]] && stow --restow $(find . -type d -maxdepth 1 | cut -c 3- | tr "\n" " ")

# clone repos

# this should come after anything involving Homebrew
# because the ~/.zprofile won't be picked up, and hence
# no Homebrew loading nor related env varialbes
- name: Change the default location of ZSH rc files
  become: true
  ansible.builtin.copy:
    dest: /etc/zshenv
    content: 'export ZDOTDIR="$HOME/.config/zsh"'
    owner: root
    mode: u=rw,g=r,o=r
