- name: Install ZSH with Homebrew
  tags: homebrew
  community.general.homebrew:
    name: zsh
    state: present

- name: Make it the default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ ansible_env.HOMEBREW_PREFIX }}/bin/zsh"
    # It seems there is no need to include the path in /etc/shells

# TODO: populate the brews and casks txt files with essential development packages and stuff loaded in zsh rc files
# This is to avoid errors when those are copied over in the dotfiles task
- name: Install essential apps and packages
  block:
    - name: 1. Install essential brews
      tags: homebrew
      community.general.homebrew:
        name: "{{ lookup('file', 'homebrew_brews.txt') | replace('\n', ',') }}"
        state: present

    # NOTE: homebrew_cask module is used because homebrew is problematic
    # for casks: e.g. failing if the cask is already installed.
    - name: 2. Install essential casks
      tags: homebrew
      community.general.homebrew_cask:
        name: "{{ lookup('file', 'homebrew_casks.txt') | replace('\n', ',') }}"
        state: present
        install_options: no-quarantine

    # NOTE: this is not needed now as App Store apps will be installed
    # from the Brewfile
    # NOTE: you need to be signed in to the Mac App Store with Apple ID
    # - name: Install App Store apps with mas
      # community.general.mas:
        # id:
          # - 12345
          # - 12345
        # state: present

- name: Setup language-specific version managers
  ansible.builtin.include_tasks: version_managers.yml

  # GNU Stow was buggy when absolute paths were used
- name: Symlink all dotfiles using a crude script
  tags: dotfiles
  ansible.builtin.script:
    cmd: dotfiles.sh

# this should come after anything involving Homebrew
# because the ~/.zprofile won't be picked up, and hence
# no Homebrew loading nor related env varialbes
- name: Change the default location of ZSH rc files
  become: true
  ansible.builtin.copy:
    dest: /etc/zshenv
    content: 'export ZDOTDIR="$HOME/.config/zsh"'
    owner: root
    mode: u=rw,g=r,o=r

# TODO: clone repos

# TODO: change system settings

# sign in to app store

  # NOTE: this task takes a very long time when many apps need to be installed.
  # TODO: find a way to log the output to the terminal, as it's a long command.
  # and fine a way of ignoring errors of specific kind (if mas apps fail to install) due to forgetting to sign in to Apple ID
- name: Install all other apps (including App Store ones) from Brewfile
  tags: homebrew
  register: brewfile_cmd_output
  environment:
    HOMEBREW_CASK_OPTS: --no-quarantine
  ansible.builtin.shell:
    chdir: "{{ ansible_env.HOME }}/.dotfiles/Homebrew"
    cmd: brew bundle install --verbose --file=./Brewfile

- name: Homebrew cleanup
  ansible.builtin.command: brew cleanup --verbose --prune=all

# TODO: explore tips found here: https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f

# NOTE: ansible_env is used to access env variables on the remote machine.
# It's part of ansible facts collected about the remote node.

# NOTE: lookup always accesses data on the control node, but
# the control node and the remote node are the same machine here.
