require("core.plugin_config.catppuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.vim-fugitive")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.undotree")
