# TODO: find a way to clone the repo to $HOME/.dotfiles
name: CI for MacOS machine setup

on:
  workflow_dispatch: # be able to run the workflow manually
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  test-ansible-role:
    runs-on: macos-latest
    # env:
    #   SUPER_SECRET: $ {{secrets.ANISBLE_VAULT}}

    steps:
      - name: Checkout dotfiles repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
          path: .dotfiles

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install latest version of Ansible
        run: |
          python3 -m pip install --user --no-warn-script-location ansible
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Run the Ansible playbook
        working-directory: ${{ github.workspace }}/.dotfiles
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
        run: |
          echo "$ANSIBLE_VAULT_PASS" > ./vault_pass 
          ansible-playbook local.yml --ask-become-pass --vault-pass-file ./vault_pass --skip-tags all_apps
          rm ./vault_pass
